services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data  
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb


  pgadmin:
    image: dpage/pgadmin4:6.21
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    user: root  # Run as root
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

volumes:
  postgres-data:
