name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2] # Uses 2 parallel instances
    steps:
      # Checkout the code first
      - name: Checkout
        uses: actions/checkout@v4

      # Debug: Print the current directory structure
      - name: Print Current Directory
        run: pwd

      - name: List All Files
        run: ls -R

      # Navigate to the threadhiveblog directory and install dependencies
      - name: Install Dependencies
        run: npm install
        working-directory: threadhiveblog

      # Run Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: threadhiveblog
